#!/usr/bin/env node
/**
 * configure-build.mjs — generate www/js/kernel_config.js from build-profiles.json.
 *
 * Picks a profile (BUILD_PROFILE env var, or first CLI arg, or the file's
 * "default"), then emits the runtime config the app reads at load time:
 *   window.KERNEL_CONFIG = { profile, languages: { <lang>: {enabled, runtime, timeoutMs, sources} } }
 *
 * `enabled` reflects the chosen profile's language set; `timeoutMs`/`sources`
 * come from the stable per-language metadata. Bundling of swipl/pyodide is
 * deferred — a profile's `bundle` list is reported but not yet acted on (no
 * vendor copy / SW precache injection happens here yet).
 *
 * Usage:
 *   node scripts/configure-build.mjs            # uses default profile
 *   node scripts/configure-build.mjs mini       # explicit profile
 *   BUILD_PROFILE=light node scripts/configure-build.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const PROFILES_PATH = join(ROOT, 'build-profiles.json');
const OUTPUT_PATH = join(ROOT, 'www', 'js', 'kernel_config.js');

function fail(msg) {
  console.error('[configure-build] ' + msg);
  process.exit(1);
}

const spec = JSON.parse(readFileSync(PROFILES_PATH, 'utf8'));
const profileName = process.env.BUILD_PROFILE || process.argv[2] || spec.default;

const profile = spec.profiles && spec.profiles[profileName];
if (!profile) {
  fail(`unknown profile '${profileName}'. Known: ${Object.keys(spec.profiles || {}).join(', ')}`);
}

const enabledSet = new Set(profile.enabled || []);
const bundleSet = new Set(profile.bundle || []);

// Build the languages map: every known language, with enabled set by the profile.
const langs = {};
for (const [name, meta] of Object.entries(spec.languages)) {
  const entry = {
    enabled: enabledSet.has(name),
    runtime: meta.runtime || 'cdn',
    timeoutMs: meta.timeoutMs || 0,
    sources: (meta.sources || []).slice(),
  };
  // If this profile bundles the language, prepend a local source and mark it
  // preferred so the runtime tries the bundled copy first (offline-capable,
  // CDN as fallback). The asset is fetched by scripts/fetch-bundles.mjs.
  if (bundleSet.has(name) && meta.localUrl) {
    entry.sources.unshift({ type: 'local', url: meta.localUrl });
    entry.preferLocal = true;
  }
  langs[name] = entry;
}

// Warn about anything the profile references that we don't know about.
for (const name of enabledSet) {
  if (!spec.languages[name]) fail(`profile '${profileName}' enables unknown language '${name}'`);
}

const config = { profile: profileName, languages: langs };

const banner =
`/**
 * kernel_config.js — AUTO-GENERATED by scripts/configure-build.mjs.
 *
 * Do NOT edit by hand. Edit build-profiles.json and re-run:
 *   node scripts/configure-build.mjs [profile]
 *   BUILD_PROFILE=mini node scripts/configure-build.mjs
 *
 * Generated for profile: ${profileName}
 *
 * The runtime (KernelManager.loadKernelSource) reads each language's
 * timeoutMs + sources to load its CDN runtime with a per-attempt timeout and
 * mirror fallbacks; \`enabled\` gates which languages the app exposes.
 * Per-kernel override: localStorage['scirepl_<lang>_source'] = a URL (tried
 * first) or 'local' (prefer a bundled source, when one exists).
 */
`;

const body = 'window.KERNEL_CONFIG = ' + JSON.stringify(config, null, 2) + ';\n';
writeFileSync(OUTPUT_PATH, banner + body);

const bundled = bundleSet.size ? ` (bundle declared: ${[...bundleSet].join(', ')} — deferred, CDN for now)` : '';
console.log(`[configure-build] wrote ${OUTPUT_PATH} for profile '${profileName}'`);
console.log(`[configure-build] enabled: ${[...enabledSet].join(', ')}${bundled}`);
